name: NugetDeploy

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Push to github
      run: dotnet nuget push ./bin/Release/*.nupkg -s https://nuget.pkg.github.com/TheJustLink/index.json --skip-duplicate -k ${{github.token}}
      
    - name: Push to nuget
      run: dotnet nuget push ./bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{secrets.NUGET_API_KEY}}
